spring.application.name=task-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_db
spring.datasource.username=student
spring.datasource.password=StudPass
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
application.security.jwt.secret-key=${JWT_SECRET:wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY+abc123/def456/ghi789/jkl012=}
application.security.jwt.expiration=900000
application.security.jwt.refresh-token.expiration=604800000