spring.application.name=task-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_db
spring.datasource.username=student
spring.datasource.password=StudPass
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml